/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "6a7b3dbec3b2ca25877c2553b5473b2f277ef644"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
