/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "75c589e1f436688fca8f5b7f7a8affeafaa4f923"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
