/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_WEBGPU_DAWN_COMMIT_HASH_H_
#define GPU_WEBGPU_DAWN_COMMIT_HASH_H_

#define DAWN_COMMIT_HASH "54b4153cfef88e048f365f99b962478f0087dfe8"

#endif  // GPU_WEBGPU_DAWN_COMMIT_HASH_H_
